from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PROMPTS_DIR = ROOT / "prompts"
INDEX_FILE = ROOT / "PROMPTS.md"


@dataclass(frozen=True)
class PromptItem:
    rel_path: str
    title: str
    description: str
    category: str


def _slug_to_title(slug: str) -> str:
    return slug.replace("-", " ").replace("_", " ").strip().title()


def read_front_matter(md_path: Path) -> dict[str, str]:
    """
    Minimal front-matter reader (no external deps).
    Expects:
      ---
      title: ...
      description: ...
      ---
    """
    text = md_path.read_text(encoding="utf-8", errors="replace").splitlines()
    if not text or text[0].strip() != "---":
        return {}

    fm: dict[str, str] = {}
    for line in text[1:]:
        if line.strip() == "---":
            break
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        fm[k.strip()] = v.strip().strip('"').strip("'")
    return fm


def collect_prompts() -> list[PromptItem]:
    if not PROMPTS_DIR.exists():
        raise SystemExit(f"Missing prompts directory: {PROMPTS_DIR}")

    items: list[PromptItem] = []
    for md_path in sorted(PROMPTS_DIR.rglob("*.md")):
        rel = md_path.relative_to(ROOT).as_posix()
        if rel == "prompts/_template.md":
            continue
        # ignore files/directories starting with "_" (aside from template)
        if any(part.startswith("_") for part in md_path.relative_to(PROMPTS_DIR).parts):
            continue

        fm = read_front_matter(md_path)
        title = fm.get("title") or _slug_to_title(md_path.stem)
        description = fm.get("description") or ""

        category = md_path.parent.relative_to(PROMPTS_DIR).parts[0] if md_path.parent != PROMPTS_DIR else "misc"
        items.append(
            PromptItem(
                rel_path=rel,
                title=title,
                description=description,
                category=category,
            )
        )

    return items


def render_index(items: list[PromptItem]) -> str:
    category_order = [
        "business",
        "career",
        "writing",
        "productivity",
        "learning",
        "health",
        "travel",
        "finance",
        "design",
        "content",
        "language",
        "entertainment",
        "mindset",
        "development",
        "misc",
    ]
    categories = {i.category for i in items}
    ordered = [c for c in category_order if c in categories] + sorted(categories - set(category_order))

    def cat_title(c: str) -> str:
        return _slug_to_title(c)

    by_cat: dict[str, list[PromptItem]] = {c: [] for c in ordered}
    for i in items:
        by_cat.setdefault(i.category, []).append(i)

    for c in by_cat:
        by_cat[c].sort(key=lambda x: x.title.lower())

    total = len(items)
    lines: list[str] = []
    lines.append("## Prompt Library")
    lines.append("")
    lines.append("> Auto-generated by `tools/build_index.py`. Do not edit by hand.")
    lines.append("")
    lines.append(f"**Total prompts:** {total}")
    lines.append("")
    lines.append("### Categories")
    lines.append("")
    for c in ordered:
        lines.append(f"- [{cat_title(c)}](#{c})")
    lines.append("")
    lines.append("---")
    lines.append("")

    for c in ordered:
        cat_items = by_cat.get(c, [])
        if not cat_items:
            continue
        lines.append(f"## {cat_title(c)}")
        lines.append("")
        lines.append(f"<a id=\"{c}\"></a>")
        lines.append("")
        for it in cat_items:
            desc = f" — {it.description}" if it.description else ""
            lines.append(f"- [{it.title}]({it.rel_path}){desc}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Build PROMPTS.md index from prompts/*")
    parser.add_argument("--check", action="store_true", help="Fail if PROMPTS.md is not up to date")
    args = parser.parse_args(argv)

    items = collect_prompts()
    content = render_index(items)

    if args.check:
        current = INDEX_FILE.read_text(encoding="utf-8", errors="replace") if INDEX_FILE.exists() else ""
        if current != content:
            print("PROMPTS.md is out of date. Run: python tools/build_index.py", file=sys.stderr)
            return 1
        return 0

    INDEX_FILE.write_text(content, encoding="utf-8")
    print(f"Wrote {INDEX_FILE.relative_to(ROOT).as_posix()} ({len(items)} prompts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))

